services:
  nginx:
    image: nginx:alpine
    container_name: HIVE_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
      target: server
    container_name: HIVE_api-gateway
    restart: unless-stopped
    env_file:
      - services/api-gateway/config/.env

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
      target: server
    container_name: HIVE_order
    restart: unless-stopped
    env_file:
      - services/order/config/.env
    depends_on:
      postgres:
        condition: service_healthy
      order-migrate:
        condition: service_completed_successfully
  
  order-migrate:
    build:
      context: .
      dockerfile: services/order/Dockerfile
      target: migrate
    command: [ "-command", "up" ]
    restart: no
    env_file:
      - services/order/config/.env
    depends_on:
      postgres:
        condition: service_healthy

  dispatch:
    build:
      context: .
      dockerfile: services/dispatch/Dockerfile
      target: server
    container_name: HIVE_dispatch
    restart: unless-stopped
    env_file:
      - services/dispatch/config/.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      dispatch-migrate:
        condition: service_completed_successfully

  dispatch-migrate:
    build:
      context: .
      dockerfile: services/dispatch/Dockerfile
      target: migrate
    command: [ "-command", "up" ]
    restart: no
    env_file:
      - services/dispatch/config/.env
    depends_on:
      postgres:
        condition: service_healthy

  telemetry:
    build:
      context: .
      dockerfile: services/telemetry/Dockerfile
      target: server
    container_name: HIVE_telemetry
    restart: unless-stopped
    env_file:
      - services/telemetry/config/.env
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  telemetry-emulator:
    build:
      context: .
      dockerfile: services/telemetry/Dockerfile
      target: emulator
    command:
      - "-addr"
      - "passthrough:///telemetry:50050"
      - "-period"
      - "500ms"
      - "-count"
      - "10"
    container_name: HIVE_telemetry-emulator
    restart: unless-stopped
    depends_on:
      telemetry:
        condition: service_started

  tracking:
    build:
      context: .
      dockerfile: services/tracking/Dockerfile
      target: grpc-server
    container_name: HIVE_tracking
    restart: unless-stopped
    env_file:
      - services/tracking/config/.env
    depends_on:
      redis:
        condition: service_healthy

  tracking-kafka:
    build:
      context: .
      dockerfile: services/tracking/Dockerfile
      target: kafka-worker
    container_name: HIVE_tracking-kafka
    restart: unless-stopped
    env_file:
      - services/tracking/config/.env
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  base:
    build:
      context: .
      dockerfile: services/base/Dockerfile
      target: server
    container_name: HIVE_base
    restart: unless-stopped
    env_file:
      - services/base/config/.env
    depends_on:
      redis:
        condition: service_healthy
      base-migrate:
        condition: service_completed_successfully

  base-migrate:
    build:
      context: .
      dockerfile: services/base/Dockerfile
      target: migrate
    command: [ "-command", "up" ]
    restart: no
    env_file:
      - services/base/config/.env
    depends_on:
      redis:
        condition: service_healthy
      base-generate:
        condition: service_completed_successfully

  base-generate:
    build:
      context: .
      dockerfile: services/base/Dockerfile
      target: generate
    command:
      - "-n"
      - "10"
    container_name: HIVE_base-generate
    restart: no
    env_file:
      - services/base/config/.env

  store:
    build:
      context: .
      dockerfile: services/store/Dockerfile
      target: server
    container_name: HIVE_store
    restart: unless-stopped
    env_file:
      - services/store/config/.env
    depends_on:
      redis:
        condition: service_healthy
      store-migrate:
        condition: service_completed_successfully

  store-migrate:
    build:
      context: .
      dockerfile: services/store/Dockerfile
      target: migrate
    command: [ "-command", "up" ]
    restart: no
    env_file:
      - services/store/config/.env
    depends_on:
      redis:
        condition: service_healthy
      store-generate:
        condition: service_completed_successfully

  store-generate:
    build:
      context: .
      dockerfile: services/store/Dockerfile
      target: generate
    command:
      - "-n"
      - "10"
    container_name: HIVE_store-generate
    restart: no
    env_file:
      - services/store/config/.env

  postgres:
    image: postgres:15
    restart: always
    container_name: HIVE_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-pg-init.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 15s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    container_name: HIVE_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 15s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    container_name: HIVE_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    restart: always
    container_name: HIVE_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 5

  kafka-init:
    image: confluentinc/cp-kafka:7.3.0
    container_name: HIVE_kafka-init
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo 'Creating Kafka topics...'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic telemetry-data --partitions 3 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic telemetry-events --partitions 3 --replication-factor 1
      echo 'Topics created successfully'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
    restart: "no"
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
