apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hive
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - jobs.yaml
  - api-gateway.yaml
  - order.yaml
  - dispatch.yaml
  - telemetry.yaml
  - tracking.yaml
  - base.yaml
  - store.yaml
  - ingress.yaml
  - pdb.yaml
