apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
  namespace: hive
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order
  namespace: hive
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dispatch
  namespace: hive
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dispatch
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: base
  namespace: hive
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: base
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: store
  namespace: hive
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: store
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tracking
  namespace: hive
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tracking
